# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s='Hi there Sam!'

In [2]:
s.split()

['Hi', 'there', 'Sam!']

In [3]:
['Hi','there','dad!']

['Hi', 'there', 'dad!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [52]:
planet = "Earth";
diameter = 12742;

In [55]:
print("The diameter of {} is {} kilometers.".format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [9]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [10]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integer from 20 to 35:")
print(array)

Array of all the even integer from 20 to 35:
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [20]:
import pandas as pd
data = [['tom',10],['nick',15],['juli',14]]
df = pd.DataFrame(data,columns=['Name','Age'])


   Name  Age
0   tom   10
1  nick   15
2  juli   14


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [51]:
from datetime import date
def numOfDays(date1, date2):
  return (date2-date1).days
date1 = date(2023, 1, 1)
date2 = date(2023, 2, 10)
print(numOfDays(date1,date2), "days")

40 days


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [49]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists,columns=['Numbers','Alphaphetic','Age'])
df

Numbers Alphaphetic  Age
0        1         aaa   22
1        2         bbb   25
2        3         ccc   24